### ISSUE TITLE
carlogicapi

### ISSUE THREAD

**Issue by farhansz** [burtonwilliamt/carlogicapi#19]
Hi,

Can you provide me some insights about the code that you wrote like how I can attack the cars and where I can exactly change the speed?

Cheers,
Farhan

**Comment by cowang4** [comment]
Hi Farhan,

We stopped working on this project last year, but there is decent documentation that may be able to answer some of your questions. The [wiki](https://github.com/burtonwilliamt/carlogicapi/wiki) has some examples. Otherwise I suggest looking on the Veins website, or the Sumo one.

The general idea though is that Veins connects a OMNeT++ network simulator and SUMO a vehicle simulator. You can change the speed of the cars in the example Veins project in the SUMO [configuration file](https://github.com/burtonwilliamt/carlogicapi/blob/master/tutorials/VeinsTutorial/simulations/demo.rou.xml).

**Comment by farhansz** [comment]
Hi Greg,

Thanks a lot for the info, can't appreciate enough for this.

Regrads,
Farhan
